// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ME.Template
{
    internal sealed partial class Vsix
    {
        public const string Id = "ME.Template.fbdbf63d-7047-4f1a-9fd1-e0b266995014";
        public const string Name = "ME.Template";
        public const string Description = @"BugraME Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "BugraME";
        public const string Tags = "";
    }
}
